### ISSUE TITLE
Recursive collections

### ISSUE THREAD

**Issue by mathiasrw** [oreillymedia/jsonform#3]
Thanks for a neat little library (og hej Rune) 

I have been playing around and cant make jfCollection contain a field thats a jfCollection.

Does it support recursive jfCollections?

**Comment by runemadsen** [comment]
Hej Mathias!

Yeah, I don't think that currently works. The library is currently a bit specific to our needs. You're more than welcome to send a PR though :)

**Comment by mathiasrw** [comment]
:+1:
